### ISSUE TITLE
Symbolic link generation related error

### ISSUE THREAD

**Issue by thexdc** [XENONnT/env_starter#8]
- In [README.md](https://github.com/XENONnT/env_starter/blob/master/README.md), symbolic link generator is: 
  ```
  [ershockley@dali-login1 ~]$ ln -s start_jupyter.py /home/ershockley/nt/computing/env_starter/start_jupyter.py
  ```
  But I think it shall be:
  ```
  [ershockley@dali-login1 ~]$ ln -s /home/ershockley/nt/computing/env_starter/start_jupyter.py start_jupyter.py
  ```
- If I set the symbolic link correctly, and run 
  ```
  ssh xudc@dali-login1.rcc.uchicago.edu /dali/lgrandi/strax/miniconda3/bin/python start_jupyter.py
  ```
  on my laptop, an error shows:
  ```
  Starting jupyter job
	  /tmp/slurmd/job12221635/slurm_script: line 18: /start_notebook.sh: No such file or directory
  Traceback (most recent call last):
    File "start_jupyter.py", line 310, in <module>
      main()
    File "start_jupyter.py", line 275, in main
      raise RuntimeError("Jupyter did not start inside your job!")
  RuntimeError: Jupyter did not start inside your job!
  ```
  I think this is because the directory of the symbolic link does not include `start_notebook.sh`.

**Comment by ershockley** [comment]
Thanks @thexdc -- I always mix this up. Must've copied the wrong line.

**Comment by ershockley** [comment]
And yeah I also see symbolic link doesn't actually work. I thought I tested it but clearly not 🤭
